### ISSUE TITLE
Collection of several translation issues

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1465]
To prevent to much commits in context of translations I'll collect such issues here and fix them all at once.

- [x] [Here](https://github.com/bit-team/backintime/blob/e44e9d64b972be2dab3aa0f94af34d44e80eabf9/qt/settingsdialog.py#L508) we have one `k` to much.

- [x] ~Check all other `MountException`'s.~ Add again all `MountException` to translatable strings because most of them result in a QMessageBox.

- [x] Professional [advice](https://www.reddit.com/r/localization/comments/14dhpkm/comment/jq7fh6r/?utm_source=share&utm_medium=web2x&context=3) about exclamation marks and other details.

- [x] [Remove one `s` from `weeks(s)`](https://github.com/bit-team/backintime/blob/e44e9d64b972be2dab3aa0f94af34d44e80eabf9/qt/settingsdialog.py#L681).

- [x] [Typo: `wethere` should be `whether`](https://github.com/bit-team/backintime/blob/e44e9d64b972be2dab3aa0f94af34d44e80eabf9/qt/settingsdialog.py#L760).

- [x] [In English "information" is always used in singular, "іnformations" is a common mistake](https://github.com/bit-team/backintime/blob/e44e9d64b972be2dab3aa0f94af34d44e80eabf9/qt/logviewdialog.py#L100) [[1]](https://dictionary.cambridge.org/grammar/british-grammar/information), [[2]](https://en.wiktionary.org/wiki/Appendix:Glossary#uncountable).

- [x] Typo: `Host` to `host` in [SettingsDialog](https://github.com/bit-team/backintime/blob/e44e9d64b972be2dab3aa0f94af34d44e80eabf9/qt/settingsdialog.py#L656C48-L656C52).

- [x] ~Bug (variable typo): [`suffx=`](https://github.com/bit-team/backintime/blob/e44e9d64b972be2dab3aa0f94af34d44e80eabf9/qt/app.py#L1078C18-L1078C18) to `suffix=`. Happens when using the _Restore_ button in the FilesView toolbar.~ Fixed via #1478.

- [x] Tranlation badge [![Translation status](https://translate.codeberg.org/widgets/backintime/-/svg-badge.svg)](https://translate.codeberg.org/engage/backintime/) `[![Translation status](https://translate.codeberg.org/widgets/backintime/-/svg-badge.svg)](https://translate.codeberg.org/engage/backintime/)`

- [x] https://github.com/bit-team/backintime/blob/1003d360d758bce78c6cd528ea41df3734fec95b/qt/app.py#L1377 `name` is a timestamp for real. Translators won't understand that.

- [x] https://github.com/bit-team/backintime/blob/df871ae6466177d154d3bb4787c30eb92339ec3a/qt/app.py#L1373 `content` -> `contents` (reported by translator [SomeTr](https://translate.codeberg.org/user/SomeTr/))

- [x] https://github.com/bit-team/backintime/blob/df871ae6466177d154d3bb4787c30eb92339ec3a/qt/settingsdialog.py#L988-L990 Remove the `e.g. path...` part from the translation string because some translators do translate the path. Suggestion: `_('Options must be quoted e.g. {example}.').format(example='--exclude-from="/path/to/my exclude file".')`

- [x] ~Think about removing `&` character from all menu entry strings to prevent shortcuts being translated, overwritten or conflicting/dupcliate with others.~ After discussions with Qt and GNU gettext folks I decided to remove them all and add shortcuts explicit via `QAction()`. -> Better think about it. Underlined characters in menubars are gone in that case. Maybe keep the decision about how to deal with `&` up to the translators.

- [x] Remove abostrophe from the end [here](https://github.com/bit-team/backintime/blob/71c9657324c0e08dd3288dbff830dd90c1cc15d2/common/config.py#L1719).

- [x] Add to TRANSLATORS list: "Scythemare" for Brazilian Portuguese (https://www.reddit.com/r/localization/comments/14dhpkm/comment/jt809ye/?utm_source=share&utm_medium=web2x&context=3)

**Comment by b100w11** [comment]
There are some issues with the slovenian translation (and i guess also with others).
Slovenian has different plural forms based on the last number of the plural (this is probably an oversimplification and the linguists will have something to complain, but it explains the issue).
So if we take an example with "knjiga" (book) we have this forms.
1 knjiga
2 knjigi
3-4 knjige
5 knjig
The same pattern repeats with "101 knjiga", "102 knjigi", ... ,  "1001 knjiga", "1002 knjigi" and so on.

The gettext solution is this
"Plural-Forms: nplurals=4; plural=(n%100==1 ? 1 : n%100==2 ? 2 : n%100==3 || n%100==4 ? 3 : 0)\n"

So it should work for every instance where there is a singular and plural form.
Something similar should also solve the "day(s)" problem in English and other languages.
I don't know where to incorporate this.
