### ISSUE TITLE
Migrate user manual to MkDocs

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1838]
This is a meta issue to coordinate and document the steps migrating our documentation to MkDocs.

- [X] Initial MkDocs setup incl. the user manual content (PR #1837)
- [X] Document build dependencies to generate the doc.
- [X] Update doc-dev documents regarding MkDocs.
- [ ] Add user-callback docu (Issue #1659)
- [ ] Consider [open issues](https://github.com/bit-team/user-callback/issues) in "user-callback" repo
- [X] Setup ReadTheDocs to use this MkDocs.
- [ ] Mark "user-callback" repo as deprecated and "Public archive".
- [X] ~~Remove "doc" repo.~~ Mark "doc" repo as deprecated and "Public archive".

# HowTo generate doc on your local system using MkDocs
To generate the doc on your local system, navigate into `/doc/manual`. Now you have to options: 1) Run `mkdocs build` to generate HTML and open `/doc/manual/html/index.html`, or 2) run `mkdocs serve` and start your browser with http://127.0.0.1:8000 ("localhost:8000" doesn't work on my system). You can modify the config and the content (md-files) life while the server runs.

**Comment by buhtz** [comment]
The user manual now is build with MkDocs by Read The Docs.
The repo bit-team/doc now has a deprecated message in the beginning of it README.md and I set the repo into "archive" mode.

**Comment by buhtz** [comment]
https://mail.python.org/archives/list/bit-dev@python.org/message/JDU4EYFYKFA6YZZD2WP2WKPE4QA5UIBA/
