### ISSUE TITLE
feature!: Improve and modify Auto-remove

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1977]
Blocked by and follow-up of #1976
Meta issue #1945

# Problem
The Auto-remove feature has potential for improvement. It is complex in some details. And the code is not organized in a way to create isolated unit tests.

# Goals
1. Refactor the code.
2. Add unit tests.
3. Modify the behavior with revising existing rules, maybe adding new rules and/or removing rules.
4. Modify user manual accordingly.

# Details about modifications considered
* [ ] Term "snapshot" to "backup" (Issue #2073)
* [x] ~~Remove? "Remove if snapshot is older than N years/months/weeks." ([ref](https://github.com/bit-team/backintime/issues/1945#issuecomment-2552119090))~~
* [x] ~~Because of that modify: "Keep one snapshot per year for all years" from QLabel to a modifyable value.~~
* [x] ~~Maybe: Time-independent rule: "No matter what, keep the NN last backups" ([ref](https://github.com/bit-team/backintime/issues/1945#issuecomment-2552119090))~~ -> Nice idea, but rejected, in favor of not increasing complexity further.
* [X] ~~Think about rules respecting each other and not overwritting. Example "Keep one monthly backup for 12 months" plus "Always keep the last 10 daily backups"~~ -> Isn't this still possible? IMHO it is.
* [X] ~~Inode/space rules: Remove them maybe.~~ -> No. Keep them.
* [ ] Separate feature: pre-warning if user-defined threshold of space/inode limit is reached. (#2110)
* [x] Ask user "ceperman" for review ([ref](https://github.com/bit-team/backintime/issues/1945#issuecomment-2558856996)).
* [x] https://github.com/bit-team/backintime/issues/1976#issuecomment-2564714561
* [X] Consider `common/backintime.py::smartRemove()`

**Comment by buhtz** [comment]
Closing this issue in favor of several follow-up issues.
